--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence QNA_COMMENT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."QNA_COMMENT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FILE_BOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_FILE_BOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FREE_BOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_FREE_BOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FREE_COMMENT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_FREE_COMMENT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LIKE_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_LIKE_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA_BOARD_COMMENT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_QNA_BOARD_COMMENT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA_BOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_QNA_BOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA_COMMENT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_QNA_COMMENT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_QNA_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERS_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_USERS_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD_LIKE
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD_LIKE" 
   (	"IDX" NUMBER, 
	"BOARD_TYPE" VARCHAR2(20 BYTE), 
	"BOARD_IDX" NUMBER, 
	"USER_IDX" NUMBER, 
	"LIKED_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FILE_BOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."FILE_BOARD" 
   (	"IDX" NUMBER, 
	"USER_IDX" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VIEWS" NUMBER DEFAULT 0, 
	"ORIGINAL_NAME" VARCHAR2(255 BYTE), 
	"SAVED_NAME" VARCHAR2(255 BYTE), 
	"FILE_TYPE" VARCHAR2(30 BYTE), 
	"FILESIZE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FREE_BOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."FREE_BOARD" 
   (	"IDX" NUMBER, 
	"USER_IDX" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VIEWS" NUMBER DEFAULT 0, 
	"LIKES" NUMBER DEFAULT 0, 
	"RECOMMEND_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FREE_BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" 
   (	"IDX" NUMBER, 
	"BOARD_IDX" NUMBER, 
	"USER_IDX" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"POSTDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QNA_BOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."QNA_BOARD" 
   (	"IDX" NUMBER, 
	"USER_IDX" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"VIEWS" NUMBER DEFAULT 0, 
	"GNUM" NUMBER, 
	"ONUM" NUMBER DEFAULT 0, 
	"DEPTH" NUMBER DEFAULT 0, 
	"REPLY_STATE" NUMBER(1,0) DEFAULT 0, 
	"PARENT_IDX" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table QNA_BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" 
   (	"IDX" NUMBER, 
	"BOARD_IDX" NUMBER, 
	"USER_IDX" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"POSTDATE" DATE DEFAULT SYSDATE, 
	"PARENT_IDX" NUMBER DEFAULT 0, 
	"DEPTH" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."USERS" 
   (	"IDX" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"PW" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into WEBPROJECT_DB.BOARD_LIKE
SET DEFINE OFF;
Insert into WEBPROJECT_DB.BOARD_LIKE (IDX,BOARD_TYPE,BOARD_IDX,USER_IDX,LIKED_DATE) values (2,'free',3,1,to_date('25/12/09','RR/MM/DD'));
Insert into WEBPROJECT_DB.BOARD_LIKE (IDX,BOARD_TYPE,BOARD_IDX,USER_IDX,LIKED_DATE) values (3,'free',14,1,to_date('25/12/10','RR/MM/DD'));
Insert into WEBPROJECT_DB.BOARD_LIKE (IDX,BOARD_TYPE,BOARD_IDX,USER_IDX,LIKED_DATE) values (9,'free',13,1,to_date('25/12/12','RR/MM/DD'));
REM INSERTING into WEBPROJECT_DB.FILE_BOARD
SET DEFINE OFF;
Insert into WEBPROJECT_DB.FILE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,ORIGINAL_NAME,SAVED_NAME,FILE_TYPE,FILESIZE) values (2,1,'222',to_date('25/12/10','RR/MM/DD'),20,'dog.png','56bedf15-1014-4562-8fd6-84ec55324187.png',null,68438);
Insert into WEBPROJECT_DB.FILE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,ORIGINAL_NAME,SAVED_NAME,FILE_TYPE,FILESIZE) values (1,1,'111',to_date('25/12/10','RR/MM/DD'),2,'1.png','16fe2bee-c1e0-476b-8cff-1b72c01043a4.png','png',179567);
Insert into WEBPROJECT_DB.FILE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,ORIGINAL_NAME,SAVED_NAME,FILE_TYPE,FILESIZE) values (3,1,'2222',to_date('25/12/12','RR/MM/DD'),1,null,null,null,0);
REM INSERTING into WEBPROJECT_DB.FREE_BOARD
SET DEFINE OFF;
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (4,1,'222',to_date('25/12/09','RR/MM/DD'),0,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (3,1,'111',to_date('25/12/09','RR/MM/DD'),33,0,1);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (5,1,'333',to_date('25/12/09','RR/MM/DD'),0,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (6,1,'444',to_date('25/12/09','RR/MM/DD'),0,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (7,1,'555',to_date('25/12/09','RR/MM/DD'),0,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (8,1,'666',to_date('25/12/09','RR/MM/DD'),0,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (9,1,'777',to_date('25/12/09','RR/MM/DD'),0,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (10,1,'888',to_date('25/12/09','RR/MM/DD'),0,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (11,1,'999',to_date('25/12/09','RR/MM/DD'),1,0,0);
Insert into WEBPROJECT_DB.FREE_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,LIKES,RECOMMEND_COUNT) values (13,1,'111111',to_date('25/12/12','RR/MM/DD'),7,0,1);
REM INSERTING into WEBPROJECT_DB.FREE_BOARD_COMMENT
SET DEFINE OFF;
Insert into WEBPROJECT_DB.FREE_BOARD_COMMENT (IDX,BOARD_IDX,USER_IDX,CONTENT,POSTDATE) values (21,13,1,'메롱',to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.FREE_BOARD_COMMENT (IDX,BOARD_IDX,USER_IDX,CONTENT,POSTDATE) values (1,3,1,'111',to_date('25/12/09','RR/MM/DD'));
REM INSERTING into WEBPROJECT_DB.QNA_BOARD
SET DEFINE OFF;
Insert into WEBPROJECT_DB.QNA_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,GNUM,ONUM,DEPTH,REPLY_STATE,PARENT_IDX) values (10,1,'111',to_date('25/12/10','RR/MM/DD'),11,10,0,0,1,0);
Insert into WEBPROJECT_DB.QNA_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,GNUM,ONUM,DEPTH,REPLY_STATE,PARENT_IDX) values (11,2,'RE: 222',to_date('25/12/10','RR/MM/DD'),4,10,1,1,1,0);
Insert into WEBPROJECT_DB.QNA_BOARD (IDX,USER_IDX,TITLE,POSTDATE,VIEWS,GNUM,ONUM,DEPTH,REPLY_STATE,PARENT_IDX) values (12,1,'555',to_date('25/12/12','RR/MM/DD'),1,12,0,0,0,0);
REM INSERTING into WEBPROJECT_DB.QNA_BOARD_COMMENT
SET DEFINE OFF;
Insert into WEBPROJECT_DB.QNA_BOARD_COMMENT (IDX,BOARD_IDX,USER_IDX,CONTENT,POSTDATE,PARENT_IDX,DEPTH) values (2,10,1,'메롱메롱',to_date('25/12/11','RR/MM/DD'),0,0);
Insert into WEBPROJECT_DB.QNA_BOARD_COMMENT (IDX,BOARD_IDX,USER_IDX,CONTENT,POSTDATE,PARENT_IDX,DEPTH) values (3,12,1,'123',to_date('25/12/12','RR/MM/DD'),0,0);
Insert into WEBPROJECT_DB.QNA_BOARD_COMMENT (IDX,BOARD_IDX,USER_IDX,CONTENT,POSTDATE,PARENT_IDX,DEPTH) values (5,11,1,'111',to_date('25/12/12','RR/MM/DD'),0,0);
REM INSERTING into WEBPROJECT_DB.USERS
SET DEFINE OFF;
Insert into WEBPROJECT_DB.USERS (IDX,ID,PW,NAME,EMAIL,PHONE,REGDATE) values (2,'111','111','김개똥','123@naver.com','01011111111',to_date('25/12/09','RR/MM/DD'));
Insert into WEBPROJECT_DB.USERS (IDX,ID,PW,NAME,EMAIL,PHONE,REGDATE) values (1,'musthave','12345','홍길동','123@naver.com','01011111111',to_date('25/12/08','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008411
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008411" ON "WEBPROJECT_DB"."USERS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008412
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008412" ON "WEBPROJECT_DB"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008426
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008426" ON "WEBPROJECT_DB"."QNA_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008448
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008448" ON "WEBPROJECT_DB"."FREE_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008453
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008453" ON "WEBPROJECT_DB"."BOARD_LIKE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008459
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008459" ON "WEBPROJECT_DB"."FREE_BOARD_COMMENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008472
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008472" ON "WEBPROJECT_DB"."FILE_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008478
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008478" ON "WEBPROJECT_DB"."QNA_BOARD_COMMENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."UQ_LIKE" ON "WEBPROJECT_DB"."BOARD_LIKE" ("BOARD_TYPE", "BOARD_IDX", "USER_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008453
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008453" ON "WEBPROJECT_DB"."BOARD_LIKE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."UQ_LIKE" ON "WEBPROJECT_DB"."BOARD_LIKE" ("BOARD_TYPE", "BOARD_IDX", "USER_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008472
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008472" ON "WEBPROJECT_DB"."FILE_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008448
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008448" ON "WEBPROJECT_DB"."FREE_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008459
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008459" ON "WEBPROJECT_DB"."FREE_BOARD_COMMENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008426
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008426" ON "WEBPROJECT_DB"."QNA_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008478
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008478" ON "WEBPROJECT_DB"."QNA_BOARD_COMMENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008411
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008411" ON "WEBPROJECT_DB"."USERS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008412
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008412" ON "WEBPROJECT_DB"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD_LIKE
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD_LIKE" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_LIKE" MODIFY ("BOARD_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_LIKE" MODIFY ("USER_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD_LIKE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."BOARD_LIKE" ADD CONSTRAINT "UQ_LIKE" UNIQUE ("BOARD_TYPE", "BOARD_IDX", "USER_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FILE_BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FILE_BOARD" MODIFY ("USER_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FILE_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FILE_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FILE_BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FILE_BOARD" MODIFY ("VIEWS" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FILE_BOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FREE_BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" MODIFY ("USER_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" MODIFY ("VIEWS" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" MODIFY ("LIKES" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" MODIFY ("RECOMMEND_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" MODIFY ("BOARD_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" MODIFY ("USER_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QNA_BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("USER_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("VIEWS" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("GNUM" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("ONUM" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("DEPTH" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" MODIFY ("REPLY_STATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" MODIFY ("BOARD_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" MODIFY ("USER_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."USERS" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."USERS" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."USERS" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."USERS" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FILE_BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FILE_BOARD" ADD CONSTRAINT "FK_FILE_USER" FOREIGN KEY ("USER_IDX")
	  REFERENCES "WEBPROJECT_DB"."USERS" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FREE_BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD" ADD CONSTRAINT "FK_FREE_USER" FOREIGN KEY ("USER_IDX")
	  REFERENCES "WEBPROJECT_DB"."USERS" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FREE_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" ADD CONSTRAINT "FK_FREE_COMMENT_BOARD" FOREIGN KEY ("BOARD_IDX")
	  REFERENCES "WEBPROJECT_DB"."FREE_BOARD" ("IDX") ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."FREE_BOARD_COMMENT" ADD CONSTRAINT "FK_FREE_COMMENT_USER" FOREIGN KEY ("USER_IDX")
	  REFERENCES "WEBPROJECT_DB"."USERS" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNA_BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD" ADD CONSTRAINT "FK_QNA_USER" FOREIGN KEY ("USER_IDX")
	  REFERENCES "WEBPROJECT_DB"."USERS" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNA_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" ADD CONSTRAINT "FK_QNA_BOARD_COMMENT" FOREIGN KEY ("BOARD_IDX")
	  REFERENCES "WEBPROJECT_DB"."QNA_BOARD" ("IDX") ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."QNA_BOARD_COMMENT" ADD CONSTRAINT "FK_QNA_BOARD_COMMENT_USER" FOREIGN KEY ("USER_IDX")
	  REFERENCES "WEBPROJECT_DB"."USERS" ("IDX") ENABLE;
